data-sources:
  data-sources:
  - name: data-base-1
    strategy: postgres
    url: jdbc:postgresql://localhost:5433/db1
    table: users
    user: postgres
    password: postgres
    mapping:
      id: user_id
      username: login
      name: first_name
      surname: last_name
  - name: data-base-2
    strategy: mysql
    url: jdbc:mysql://localhost:3306/db2
    table: users
    user: root
    password: mysql
    mapping:
      id: user_id
      username: login
      name: first_name
      surname: last_name

spring:
  jpa:
    open-in-view: false

springdoc:
  swagger-ui:
    path: "/swagger-ui.html"