data-sources:
  data-sources:
  - name: data-base-1
    url: jdbc:postgresql://localhost:5432/postgres
    table: users
    user: postgres
    password: postgres
    mapping:
      id: user_id
      username: login
      name: first_name
      surname: last_name
  - name: data-base-2
    url: jdbc:postgresql://localhost:5432/db2
    table: user_table
    user: testuser
    password: testpass
    mapping:
      id: ldap_login
      username: ldap_login
      name: name
      surname: surname

